# WARNING: automatically generated file
# Generated by 'gem nix' command that comes from 'nix' gem
g: # Get dependencies from patched gems
{
  aliases = {
    archive_tar_minitar = g.archive_tar_minitar_0_5_2;
    docker_api = g.docker_api_1_7_6;
    excon = g.excon_0_42_1;
    json = g.json_1_8_1;
    little_plugger = g.little_plugger_1_1_3;
    logging = g.logging_1_8_2;
    multi_json = g.multi_json_1_10_1;
    synapse = g.synapse_0_11_1;
    zk = g.zk_1_9_4;
    zookeeper = g.zookeeper_1_4_9;
  };
  gem_nix_args = [ ''synapse'' ];
  gems = {
    archive_tar_minitar_0_5_2 = {
      basename = ''archive_tar_minitar'';
      meta = {
        description = ''Provides POSIX tarchive management from Ruby programs.'';
        homepage = ''http://rubyforge.org/projects/ruwiki/'';
        longDescription = ''Archive::Tar::Minitar is a pure-Ruby library and command-line utility that provides the ability to deal with POSIX tar(1) archive files. The implementation is based heavily on Mauricio Ferna'ndez's implementation in rpa-base, but has been reorganised to promote reuse in other projects.'';
      };
      name = ''archive-tar-minitar-0.5.2'';
      requiredGems = [  ];
      sha256 = ''1j666713r3cc3wb0042x0wcmq2v11vwwy5pcaayy5f0lnd26iqig'';
    };
    docker_api_1_7_6 = {
      basename = ''docker_api'';
      meta = {
        description = ''A simple REST client for the Docker Remote API'';
        homepage = ''https://github.com/swipely/docker-api'';
        longDescription = ''A simple REST client for the Docker Remote API'';
      };
      name = ''docker-api-1.7.6'';
      requiredGems = [ g.excon_0_42_1 g.json_1_8_1 g.archive_tar_minitar_0_5_2 ];
      sha256 = ''1ari4f2rk9w5j5mci7wlqiabqispd2pr9m6qwbqq1ryrlqvksr28'';
    };
    excon_0_42_1 = {
      basename = ''excon'';
      meta = {
        description = ''speed, persistence, http(s)'';
        homepage = ''https://github.com/excon/excon'';
        longDescription = ''EXtended http(s) CONnections'';
      };
      name = ''excon-0.42.1'';
      requiredGems = [  ];
      sha256 = ''1za1jmp83149qmykih2bfgxlwyyz3hrpaq4kxww7467fvgwh58xj'';
    };
    json_1_8_1 = {
      basename = ''json'';
      meta = {
        description = ''JSON Implementation for Ruby'';
        homepage = ''http://flori.github.com/json'';
        longDescription = ''This is a JSON implementation as a Ruby extension in C.'';
      };
      name = ''json-1.8.1'';
      requiredGems = [  ];
      sha256 = ''0002bsycvizvkmk1jyv8px1hskk6wrjfk4f7x5byi8gxm6zzn6wn'';
    };
    little_plugger_1_1_3 = {
      basename = ''little_plugger'';
      meta = {
        description = ''LittlePlugger is a module that provides Gem based plugin management.'';
        homepage = ''http://gemcutter.org/gems/little-plugger'';
        longDescription = ''LittlePlugger is a module that provides Gem based plugin management.
By extending your own class or module with LittlePlugger you can easily
manage the loading and initializing of plugins provided by other gems.'';
      };
      name = ''little-plugger-1.1.3'';
      requiredGems = [  ];
      sha256 = ''0crxv0yl5iwmqzj2y7hh9s7qbwr7s7305vgdbsanbzq059ca98yp'';
    };
    logging_1_8_2 = {
      basename = ''logging'';
      meta = {
        description = ''A flexible and extendable logging library for Ruby'';
        homepage = ''http://rubygems.org/gems/logging'';
        longDescription = ''Logging is a flexible logging library for use in Ruby programs based on the
design of Java's log4j library. It features a hierarchical logging system,
custom level names, multiple output destinations per log event, custom
formatting, and more.'';
      };
      name = ''logging-1.8.2'';
      requiredGems = [ g.little_plugger_1_1_3 g.multi_json_1_10_1 ];
      sha256 = ''0vcckpk3sffhz9phpzkbbqzzcffsg2n292rmq5b4gx6dp9g4n86p'';
    };
    multi_json_1_10_1 = {
      basename = ''multi_json'';
      meta = {
        description = ''A common interface to multiple JSON libraries.'';
        homepage = ''http://github.com/intridea/multi_json'';
        longDescription = ''A common interface to multiple JSON libraries, including Oj, Yajl, the JSON gem (with C-extensions), the pure-Ruby JSON gem, NSJSONSerialization, gson.rb, JrJackson, and OkJson.'';
      };
      name = ''multi_json-1.10.1'';
      requiredGems = [  ];
      sha256 = ''1ll21dz01jjiplr846n1c8yzb45kj5hcixgb72rz0zg8fyc9g61c'';
    };
    synapse_0_11_1 = {
      basename = ''synapse'';
      meta = {
        description = '': Write a gem summary'';
        longDescription = '': Write a gem description'';
      };
      name = ''synapse-0.11.1'';
      requiredGems = [ g.zk_1_9_4 g.docker_api_1_7_6 ];
      sha256 = ''121ls0ypbz7i24acrldq8dzp8z6a4brl4vxngy51asgjwpalrx52'';
    };
    zk_1_9_4 = {
      basename = ''zk'';
      meta = {
        description = ''A high-level wrapper around the zookeeper driver'';
        homepage = ''https://github.com/slyphon/zk'';
        longDescription = ''A high-level wrapper around the zookeeper driver
'';
      };
      name = ''zk-1.9.4'';
      requiredGems = [ g.zookeeper_1_4_9 g.logging_1_8_2 ];
      sha256 = ''1rgghyhnbqp7lcn0vik3rn93msv51igsh5cwag88rp6hhnvd141j'';
    };
    zookeeper_1_4_9 = {
      basename = ''zookeeper'';
      meta = {
        description = ''Apache ZooKeeper driver for Rubies'';
        homepage = ''https://github.com/slyphon/zookeeper'';
        longDescription = ''A low-level multi-Ruby wrapper around the ZooKeeper API bindings. For a
friendlier interface, see http://github.com/slyphon/zk. Currently supported:
MRI: {1.8.7, 1.9.2, 1.9.3}, JRuby: ~&gt; 1.6.7, Rubinius: 2.0.testing, REE 1.8.7.

This library uses version 3.4.5 of zookeeper bindings.

'';
      };
      name = ''zookeeper-1.4.9'';
      requiredGems = [  ];
      sha256 = ''1zjb8sri15nqyqv1w9v34dv2d7q1lf3phr126mcfrj8v6vawhzcc'';
    };
  };
}
